### ISSUE TITLE
new layout for the big screen

### ISSUE THREAD

**Issue by tabascoeye** [raumzeitlabor/infoscreen#14]
New InfoScreen resolution is 1920x1200, so we need to re-design the layout.

Ideas:
- Take the twitter widget into a seperate column on the right, full height to display more tweets (also check if the twitter widget somehow supports showing retweets only once!)
- make the RNV widget bigger (mor readable fonts, more lines of info)
- make the graphs either bigger of display more of them (MOAR!)
- have a full width row on the bottom for lines from the ticket system (dynamic TODO list)

**Comment by silsha** [comment]
https://stackoverflow.com/questions/18449918/100-width-twitter-bootstrap-3-template
