### ISSUE TITLE
The RNV table is too small on the new big screen

### ISSUE THREAD

**Issue by tabascoeye** [raumzeitlabor/infoscreen#20]
The timetable that we pull via rnv.php is too tiny to read from a distance on the new big screen.
Should be doable only in CSS.

**Comment by silsha** [comment]
Einfach `.rnvtable td` eine `font-size` in der gewünschten Größe geben.

**Comment by tabascoeye** [comment]
nope. It's a bit harder than that because RNV has a fixed "width" in one of the <td> so the table won't grow with the font.
But I fixed it. Will commit in a second
